-- Eliminar completamente el usuario admin y recrearlo
DELETE FROM public.user_roles WHERE user_id = 'b368b770-ffb2-4e7a-8709-ec51aa59759d';
DELETE FROM public.profiles WHERE id = 'b368b770-ffb2-4e7a-8709-ec51aa59759d';
DELETE FROM auth.users WHERE id = 'b368b770-ffb2-4e7a-8709-ec51aa59759d';

-- Crear nuevo usuario admin directamente
INSERT INTO auth.users (
  id,
  instance_id,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'admin@padeltorneos.com',
  crypt('admin123', gen_salt('bf')),
  now(),
  now(),
  null,
  null,
  '',
  '',
  '',
  null,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"email": "admin@padeltorneos.com", "full_name": "Super Administrador"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null
);