// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvmokakgnclbmksaaear.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bW9rYWtnbmNsYm1rc2FhZWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDczMTksImV4cCI6MjA3MzgyMzMxOX0.8FDRyjawzRJOdsnNe3c_n3ulu2Zoe6BDGbLAeflj-Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});